/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin (Demo version) V5.24.            *
*        Compiled Jan 27 2014, 08:56:32                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
*        May not be used in a product                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: gps_flag1                                             *
* Dimensions:  13 * 13                                               *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmgps_flag1;

static GUI_CONST_STORAGE unsigned short _acgps_flag1[] = {
  0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x014F, 0x0193, 0x014F, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x014F, 0x014F, 0x014F, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x014F, 0x014F, 0xFD96, 0x014F, 0xFD96, 0x014F, 0x014F, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0x014F, 0xFD96, 0xFD96, 0xBEFE, 0x014F, 0xBEFE, 0xFD96, 0xFD96, 0x014F, 0x0000, 0x0000,
  0x0000, 0x0000, 0x014F, 0xFD96, 0xCF7F, 0xCF7F, 0xCF7F, 0xBEFE, 0xAE7E, 0xFD96, 0x014F, 0x0000, 0x0000,
  0x0000, 0x014F, 0xFD96, 0xBEFE, 0xCF7F, 0xCF7F, 0xCF7F, 0xBEFE, 0xBEFE, 0xAE7E, 0xFD96, 0x014F, 0x0000,
  0x0000, 0x014F, 0x014F, 0x014F, 0xBEFE, 0xCF7F, 0xCF7F, 0xBEFE, 0xAE7E, 0x014F, 0x014F, 0x014F, 0x0000,
  0x0000, 0x014F, 0xFD96, 0xAE7E, 0xBEFE, 0xBEFE, 0xBEFE, 0xAE7E, 0xAE7E, 0xAE7E, 0xFD96, 0x014F, 0x0000,
  0x0000, 0x0000, 0x014F, 0xFD96, 0xAE7E, 0xAE7E, 0xAE7E, 0xAE7E, 0xAE7E, 0xFD96, 0x014F, 0x0000, 0x0000,
  0x0000, 0x0000, 0x014F, 0xFD96, 0xFD96, 0xAE7E, 0x014F, 0xAE7E, 0xFD96, 0xFD96, 0x014F, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x014F, 0x014F, 0xFD96, 0x014F, 0xFD96, 0x014F, 0x014F, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x014F, 0x014F, 0x014F, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000
};

GUI_CONST_STORAGE GUI_BITMAP bmgps_flag1 = {
  13, // xSize
  13, // ySize
  26, // BytesPerLine
  16, // BitsPerPixel
  (unsigned char *)_acgps_flag1,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMPM565
};

/*************************** End of file ****************************/
