/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin (Demo version) V5.24.            *
*        Compiled Jan 27 2014, 08:56:32                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
*        May not be used in a product                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: network_weak                                          *
* Dimensions:  13 * 13                                               *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmnetwork_weak;

static GUI_CONST_STORAGE unsigned short _acnetwork_weak[] = {
  0x0000, 0x0000, 0x0000, 0x3186, 0x9CD3, 0xE71C, 0xFFFF, 0xE71C, 0x9CD3, 0x3186, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0841, 0x8C71, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0x8C71, 0x0841, 0x0000,
  0x0000, 0x8C71, 0xFFFF, 0xFFFF, 0xFFFF, 0xEF7D, 0xD6DA, 0xEF7D, 0xFFFF, 0xFFFF, 0xFFFF, 0x8C71, 0x0000,
  0x3186, 0xFFFF, 0xFFFF, 0xFFFF, 0xA534, 0x4A69, 0x3186, 0x4A49, 0xA534, 0xFFFF, 0xFFFF, 0xFFFF, 0x3186,
  0x9CF3, 0xFFFF, 0xFFFF, 0xA534, 0x0861, 0x0000, 0x0000, 0x0000, 0x0861, 0xA534, 0xFFFF, 0xFFFF, 0x9CF3,
  0xE73C, 0xFFFF, 0xEF7D, 0x4A69, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x4A69, 0xEF7D, 0xFFFF, 0xDF1B,
  0xFFFF, 0xFFFF, 0xD6BA, 0x3186, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x3186, 0xD6BA, 0xFFFF, 0xFFDF,
  0xE73C, 0xFFFF, 0xEF7D, 0x4A69, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x4A69, 0xEF7D, 0xFFFF, 0xDF1B,
  0x9CF3, 0xFFFF, 0xFFFF, 0xA534, 0x0861, 0x0000, 0x0000, 0x0000, 0x0861, 0xA534, 0xFFFF, 0xFFFF, 0x9CF3,
  0x3186, 0xFFFF, 0xFFFF, 0xFFFF, 0xA534, 0x4A49, 0x3186, 0x4A49, 0xA534, 0xFFFF, 0xFFFF, 0xFFFF, 0x3186,
  0x0000, 0x8C71, 0xFFFF, 0xFFFF, 0xFFFF, 0xEF7D, 0xD6BA, 0xEF7D, 0xFFFF, 0xFFFF, 0xFFFF, 0x8C71, 0x0000,
  0x0000, 0x0841, 0x8C71, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0x8C71, 0x0841, 0x0000,
  0x0000, 0x0000, 0x0000, 0x3186, 0x9CD3, 0xDEFB, 0xFFDF, 0xDF1B, 0x9CD3, 0x3186, 0x0000, 0x0000, 0x0000
};

GUI_CONST_STORAGE GUI_BITMAP bmnetwork_weak = {
  13, // xSize
  13, // ySize
  26, // BytesPerLine
  16, // BitsPerPixel
  (unsigned char *)_acnetwork_weak,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMPM565
};

/*************************** End of file ****************************/
