/* Copyright Statement:
*
* (C) 2005-2017  MediaTek Inc. All rights reserved.
*
* This software/firmware and related documentation ("MediaTek Software") are
* protected under relevant copyright laws. The information contained herein
* is confidential and proprietary to MediaTek Inc. ("MediaTek") and/or its licensors.
* Without the prior written permission of MediaTek and/or its licensors,
* any reproduction, modification, use or disclosure of MediaTek Software,
* and information contained herein, in whole or in part, shall be strictly prohibited.
* You may only use, reproduce, modify, or distribute (as applicable) MediaTek Software
* if you have agreed to and been bound by the applicable license agreement with
* MediaTek ("License Agreement") and been granted explicit permission to do so within
* the License Agreement ("Permitted User").  If you are not a Permitted User,
* please cease any access or use of MediaTek Software immediately.
* BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
* THAT MEDIATEK SOFTWARE RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES
* ARE PROVIDED TO RECEIVER ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
* WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
* NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
* SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
* SUPPLIED WITH MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
* THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
* THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
* CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
* SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
* STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
* CUMULATIVE LIABILITY WITH RESPECT TO MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
* AT MEDIATEK'S OPTION, TO REVISE OR REPLACE MEDIATEK SOFTWARE AT ISSUE,
* OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
* MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*/
/*
 **************************************************************************/
#ifndef __NVDM_MODEM_DEFAULT_CONFIG_H__
#define __NVDM_MODEM_DEFAULT_CONFIG_H__

#define MODEM_CFG_RECOVERY_SEARCH_STEP_1_DEFAULT 0x0005
#define MODEM_CFG_RECOVERY_SEARCH_STEP_2_DEFAULT 0x000A
#define MODEM_CFG_RECOVERY_SEARCH_STEP_3_DEFAULT 0x800A
#define MODEM_CFG_RECOVERY_SEARCH_STEP_4_DEFAULT 0x0001
#define MODEM_CFG_RECOVERY_SEARCH_STEP_5_DEFAULT 0x8078
#define MODEM_CFG_RECOVERY_SEARCH_STEP_6_DEFAULT 0x9C20

/* band support bit mask*/
#define MODEM_CFG_BAND_SUPPORT_B1_MASK     (0x00000001 << 0)
#define MODEM_CFG_BAND_SUPPORT_B2_MASK     (0x00000001 << 1)
#define MODEM_CFG_BAND_SUPPORT_B3_MASK     (0x00000001 << 2)
#define MODEM_CFG_BAND_SUPPORT_B5_MASK     (0x00000001 << 3)
#define MODEM_CFG_BAND_SUPPORT_B8_MASK     (0x00000001 << 4)
#define MODEM_CFG_BAND_SUPPORT_B11_MASK    (0x00000001 << 5)
#define MODEM_CFG_BAND_SUPPORT_B12_MASK    (0x00000001 << 6)
#define MODEM_CFG_BAND_SUPPORT_B13_MASK    (0x00000001 << 7)
#define MODEM_CFG_BAND_SUPPORT_B17_MASK    (0x00000001 << 8)
#define MODEM_CFG_BAND_SUPPORT_B18_MASK    (0x00000001 << 9)
#define MODEM_CFG_BAND_SUPPORT_B19_MASK    (0x00000001 << 10)
#define MODEM_CFG_BAND_SUPPORT_B20_MASK    (0x00000001 << 11)
#define MODEM_CFG_BAND_SUPPORT_B25_MASK    (0x00000001 << 12)
#define MODEM_CFG_BAND_SUPPORT_B26_MASK    (0x00000001 << 13)
#define MODEM_CFG_BAND_SUPPORT_B28_MASK    (0x00000001 << 14)
#define MODEM_CFG_BAND_SUPPORT_B31_MASK    (0x00000001 << 15)
#define MODEM_CFG_BAND_SUPPORT_B66_MASK    (0x00000001 << 16)
#define MODEM_CFG_BAND_SUPPORT_B70_MASK    (0x00000001 << 17)
#define MODEM_CFG_BAND_SUPPORT_B21_MASK    (0x00000001 << 18)
#define MODEM_CFG_BAND_SUPPORT_B4_MASK     (0x00000001 << 19)
#define MODEM_CFG_BAND_SUPPORT_B71_MASK    (0x00000001 << 20)
#define MODEM_CFG_BAND_SUPPORT_B85_MASK    (0x00000001 << 21)
#define MODEM_CFG_BAND_SUPPORT_B14_MASK    (0x00000001 << 22)
#define MODEM_CFG_BAND_SUPPORT_B72_MASK    (0x00000001 << 23)
#define MODEM_CFG_BAND_SUPPORT_B73_MASK    (0x00000001 << 24)
#define MODEM_CFG_BAND_SUPPORT_B74_MASK    (0x00000001 << 25)

#endif
