/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin (Demo version) V5.24.            *
*        Compiled Jan 27 2014, 08:56:32                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
*        May not be used in a product                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: digit_date_div                                        *
* Dimensions:  8 * 12                                                *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmdigit_date_div;

static GUI_CONST_STORAGE unsigned short _acdigit_date_div[] = {
  0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x9CF3, 0x8C71,
  0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x630C, 0xFFFF, 0x4208,
  0x0000, 0x0000, 0x0000, 0x0000, 0x1082, 0xEF7D, 0xAD75, 0x0000,
  0x0000, 0x0000, 0x0000, 0x0000, 0x8410, 0xEF7D, 0x2104, 0x0000,
  0x0000, 0x0000, 0x0000, 0x2104, 0xFFFF, 0x8410, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0xAD75, 0xDEFB, 0x1082, 0x0000, 0x0000,
  0x0000, 0x0000, 0x4208, 0xFFFF, 0x630C, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0xDEFB, 0xBDF7, 0x0000, 0x0000, 0x0000, 0x0000,
  0x0000, 0x738E, 0xFFFF, 0x3186, 0x0000, 0x0000, 0x0000, 0x0000,
  0x1082, 0xEF7D, 0x9CF3, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  0x9CF3, 0xEF7D, 0x1082, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  0x4208, 0x3186, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000
};

GUI_CONST_STORAGE GUI_BITMAP bmdigit_date_div = {
  8, // xSize
  12, // ySize
  16, // BytesPerLine
  16, // BitsPerPixel
  (unsigned char *)_acdigit_date_div,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMPM565
};

/*************************** End of file ****************************/
