/*
 * Generated by MTK Easy PinMux Tool Version 2.4.4 for 2625. Copyright MediaTek Inc. (C) 2015.
 * 2017-12-07 15:23:27:0652
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H



#endif /* _EPT_EINT_DRV_H */
