/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin (Demo version) V5.24.            *
*        Compiled Jan 27 2014, 08:56:32                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
*        May not be used in a product                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: digit_small_5                                         *
* Dimensions:  7 * 13                                                *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmdigit_small_5;

static GUI_CONST_STORAGE unsigned short _acdigit_small_5[] = {
  0x630C, 0x8410, 0x8410, 0x8410, 0x8410, 0x8410, 0x8410,
  0xBDF7, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF,
  0xBDF7, 0xFFFF, 0x4208, 0x4208, 0x4208, 0x4208, 0x4208,
  0xBDF7, 0xFFFF, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  0xBDF7, 0xFFFF, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  0xBDF7, 0xFFFF, 0x8410, 0x8410, 0x8410, 0x8410, 0x8410,
  0xBDF7, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF,
  0x3186, 0x4208, 0x4208, 0x4208, 0x4208, 0xCE79, 0xFFFF,
  0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0xBDF7, 0xFFFF,
  0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0xBDF7, 0xFFFF,
  0x3186, 0x4208, 0x4208, 0x4208, 0x4208, 0xCE79, 0xFFFF,
  0xBDF7, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF,
  0x630C, 0x8410, 0x8410, 0x8410, 0x8410, 0x8410, 0x8410
};

GUI_CONST_STORAGE GUI_BITMAP bmdigit_small_5 = {
  7, // xSize
  13, // ySize
  14, // BytesPerLine
  16, // BitsPerPixel
  (unsigned char *)_acdigit_small_5,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMPM565
};

/*************************** End of file ****************************/
