/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin (Demo version) V5.24.            *
*        Compiled Jan 27 2014, 08:56:32                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
*        May not be used in a product                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: digit_small_percent                                   *
* Dimensions:  13 * 13                                               *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmdigit_small_percent;

static GUI_CONST_STORAGE unsigned short _acdigit_small_percent[] = {
  0x630C, 0x8410, 0x8410, 0x8410, 0x8410, 0x2104, 0x0000, 0x2104, 0x8410, 0x3186, 0x0000, 0x0000, 0x0000,
  0xBDF7, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0x4208, 0x0000, 0x8410, 0xFFFF, 0x2104, 0x0000, 0x0000, 0x0000,
  0xBDF7, 0xFFFF, 0x4208, 0x9CF3, 0xFFFF, 0x4208, 0x0000, 0xDEFB, 0xCE79, 0x0000, 0x0000, 0x0000, 0x0000,
  0xBDF7, 0xFFFF, 0x4208, 0x9CF3, 0xFFFF, 0x4208, 0x3186, 0xFFFF, 0x630C, 0x0000, 0x0000, 0x0000, 0x0000,
  0xBDF7, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0x4208, 0x9CF3, 0xFFFF, 0x1082, 0x0000, 0x0000, 0x0000, 0x0000,
  0x630C, 0x8410, 0x8410, 0x8410, 0x8410, 0x2104, 0xEF7D, 0xAD75, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x528A, 0xFFFF, 0x528A, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x9CF3, 0xEF7D, 0x2104, 0x8410, 0x8410, 0x8410, 0x8410, 0x630C,
  0x0000, 0x0000, 0x0000, 0x0000, 0x1082, 0xFFFF, 0x9CF3, 0x4208, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xBDF7,
  0x0000, 0x0000, 0x0000, 0x0000, 0x630C, 0xFFFF, 0x3186, 0x4208, 0xFFFF, 0x9CF3, 0x4208, 0xFFFF, 0xBDF7,
  0x0000, 0x0000, 0x0000, 0x0000, 0xBDF7, 0xDEFB, 0x0000, 0x4208, 0xFFFF, 0x9CF3, 0x4208, 0xFFFF, 0xBDF7,
  0x0000, 0x0000, 0x0000, 0x2104, 0xFFFF, 0x8410, 0x0000, 0x4208, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xBDF7,
  0x0000, 0x0000, 0x0000, 0x3186, 0x8410, 0x2104, 0x0000, 0x2104, 0x8410, 0x8410, 0x8410, 0x8410, 0x630C
};

GUI_CONST_STORAGE GUI_BITMAP bmdigit_small_percent = {
  13, // xSize
  13, // ySize
  26, // BytesPerLine
  16, // BitsPerPixel
  (unsigned char *)_acdigit_small_percent,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMPM565
};

/*************************** End of file ****************************/
