/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin (Demo version) V5.24.            *
*        Compiled Jan 27 2014, 08:56:32                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
*        May not be used in a product                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: gpsopen                                               *
* Dimensions:  10 * 10                                               *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmgpsopen;

static GUI_CONST_STORAGE unsigned short _acgpsopen[] = {
  0x0000, 0x0000, 0x0841, 0x4228, 0x630C, 0x632C, 0x4A49, 0x1082, 0x0000, 0x0000,
  0x0000, 0x0821, 0x52AA, 0x738E, 0x6B2D, 0x632C, 0x738E, 0x630C, 0x1082, 0x0000,
  0x0000, 0x4A49, 0x738E, 0x4208, 0x0841, 0x0821, 0x31A6, 0x738E, 0x4A49, 0x0000,
  0x0000, 0x632C, 0x632C, 0x0020, 0x0000, 0x0000, 0x0000, 0x5AEB, 0x6B4D, 0x0000,
  0x0000, 0x6B4D, 0x630C, 0x0000, 0x0000, 0x0000, 0x0000, 0x5AAB, 0x6B6D, 0x0000,
  0x0000, 0x4A49, 0x738E, 0x2945, 0x0000, 0x0000, 0x2104, 0x6B6D, 0x5AAB, 0x0000,
  0x0000, 0x10A2, 0x6B6D, 0x6B6D, 0x528A, 0x4A69, 0x6B6D, 0x738E, 0x2104, 0x0000,
  0x0000, 0x0000, 0x2104, 0x6B4D, 0x738E, 0x738E, 0x6B6D, 0x2945, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x2124, 0x738E, 0x738E, 0x2925, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x0000, 0x4A69, 0x52AA, 0x0000, 0x0000, 0x0000, 0x0000
};

GUI_CONST_STORAGE GUI_BITMAP bmgpsopen = {
  10, // xSize
  10, // ySize
  20, // BytesPerLine
  16, // BitsPerPixel
  (unsigned char *)_acgpsopen,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMPM565
};

/*************************** End of file ****************************/
