/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin (Demo version) V5.24.            *
*        Compiled Jan 27 2014, 08:56:32                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
*        May not be used in a product                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: gpssuccess                                            *
* Dimensions:  10 * 10                                               *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmgpssuccess;

static GUI_CONST_STORAGE unsigned short _acgpssuccess[] = {
  0x0000, 0x0000, 0x00C0, 0x14A3, 0x1EE4, 0x1F05, 0x14E3, 0x0121, 0x0000, 0x0000,
  0x0000, 0x00A0, 0x1664, 0x1FC5, 0x1F25, 0x1F05, 0x1FC5, 0x1EE4, 0x0121, 0x0000,
  0x0000, 0x14A3, 0x1FC5, 0x1462, 0x0080, 0x0060, 0x0BA2, 0x1FC5, 0x1563, 0x0000,
  0x0000, 0x1EE4, 0x1F04, 0x0040, 0x0000, 0x0000, 0x0000, 0x1E64, 0x1F45, 0x0000,
  0x0000, 0x1F25, 0x1EC4, 0x0000, 0x0000, 0x0000, 0x0000, 0x1604, 0x1F85, 0x0000,
  0x0000, 0x1563, 0x1FC5, 0x0AE1, 0x0000, 0x0000, 0x0A21, 0x1FA5, 0x1E24, 0x0000,
  0x0000, 0x0180, 0x1F65, 0x1FC5, 0x1563, 0x1543, 0x1FA5, 0x1FC5, 0x0221, 0x0000,
  0x0000, 0x0000, 0x0A41, 0x1F45, 0x1FC5, 0x1FC5, 0x1F85, 0x0AE2, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x0A81, 0x1FC5, 0x1FC5, 0x0AA1, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x0000, 0x1543, 0x15C4, 0x0000, 0x0000, 0x0000, 0x0000
};

GUI_CONST_STORAGE GUI_BITMAP bmgpssuccess = {
  10, // xSize
  10, // ySize
  20, // BytesPerLine
  16, // BitsPerPixel
  (unsigned char *)_acgpssuccess,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMPM565
};

/*************************** End of file ****************************/
