/*
 * Generated by MTK Easy PinMux Tool Version 2.5.4 for 2625. Copyright MediaTek Inc. (C) 2015.
 * 2019-04-22 12:47:18:0942
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*  
* Author:
* -------
*
*============================================================================
****************************************************************************/

#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H



#endif /* _EPT_EINT_DRV_H */
