/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin (Demo version) V5.24.            *
*        Compiled Jan 27 2014, 08:56:32                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
*        May not be used in a product                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: digit_hr                                              *
* Dimensions:  14 * 11                                               *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmdigit_hr;

static GUI_CONST_STORAGE unsigned short _acdigit_hr[] = {
  0x0000, 0x4000, 0xC000, 0xF800, 0xE800, 0x7000, 0x0000, 0x0000, 0x7000, 0xE800, 0xF800, 0xC000, 0x4000, 0x0000,
  0x4800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0x9800, 0x9800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0x4800,
  0xC800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xC800,
  0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800,
  0xE000, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xE000,
  0x7800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0x7800,
  0x0800, 0xC000, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xC000, 0x0800,
  0x0000, 0x1000, 0xC000, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xC000, 0x1000, 0x0000,
  0x0000, 0x0000, 0x0800, 0xA800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xA800, 0x0800, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x0000, 0x7800, 0xF800, 0xF800, 0xF800, 0xF800, 0x7800, 0x0000, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x3800, 0xD000, 0xD000, 0x3800, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000
};

GUI_CONST_STORAGE GUI_BITMAP bmdigit_hr = {
  14, // xSize
  11, // ySize
  28, // BytesPerLine
  16, // BitsPerPixel
  (unsigned char *)_acdigit_hr,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMPM565
};

/*************************** End of file ****************************/
