/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin (Demo version) V5.24.            *
*        Compiled Jan 27 2014, 08:56:32                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
*        May not be used in a product                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: digit_step                                            *
* Dimensions:  13 * 13                                               *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmdigit_step;

static GUI_CONST_STORAGE unsigned short _acdigit_step[] = {
  0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0929, 0x1253, 0x1232, 0x08A5, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0909, 0x11CE, 0x0929, 0x0000, 0x0084, 0x1AF8, 0x1B18, 0x1B18, 0x1AD6, 0x0021, 0x0000,
  0x0000, 0x096B, 0x1B18, 0x1B18, 0x1B18, 0x094A, 0x096B, 0x1B18, 0x1B18, 0x1B18, 0x1B18, 0x0929, 0x0000,
  0x0021, 0x1AD7, 0x1B18, 0x1B18, 0x1B18, 0x1232, 0x11AD, 0x1B18, 0x1B18, 0x1B18, 0x1B18, 0x11AD, 0x0000,
  0x08C6, 0x1B18, 0x1B18, 0x1B18, 0x1B18, 0x1A73, 0x118C, 0x1B18, 0x1B18, 0x1B18, 0x1B18, 0x096B, 0x0000,
  0x08C6, 0x1B18, 0x1B18, 0x1B18, 0x1B18, 0x1231, 0x0929, 0x1B18, 0x1B18, 0x1B18, 0x1B18, 0x0084, 0x0000,
  0x0022, 0x1B18, 0x1B18, 0x1B18, 0x1B18, 0x116C, 0x0885, 0x1B18, 0x1B18, 0x1B18, 0x1A94, 0x0000, 0x0000,
  0x0000, 0x1A95, 0x1B18, 0x1B18, 0x1B18, 0x08A5, 0x0000, 0x11F0, 0x1232, 0x1A94, 0x11AD, 0x0000, 0x0000,
  0x0000, 0x1211, 0x1AD7, 0x1AD7, 0x1A94, 0x0000, 0x0000, 0x0084, 0x0042, 0x0000, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x1AF8, 0x1B18, 0x1AF8, 0x0063, 0x0000, 0x0000,
  0x0000, 0x11AD, 0x1252, 0x1253, 0x08E7, 0x0000, 0x0000, 0x1AF7, 0x1B18, 0x1AD7, 0x0000, 0x0000, 0x0000,
  0x0000, 0x1211, 0x1B18, 0x1B18, 0x0908, 0x0000, 0x0000, 0x0929, 0x1232, 0x0908, 0x0000, 0x0000, 0x0000,
  0x0000, 0x08E7, 0x1AF7, 0x1A95, 0x0042, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000
};

GUI_CONST_STORAGE GUI_BITMAP bmdigit_step = {
  13, // xSize
  13, // ySize
  26, // BytesPerLine
  16, // BitsPerPixel
  (unsigned char *)_acdigit_step,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMPM565
};

/*************************** End of file ****************************/
