/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin (Demo version) V5.24.            *
*        Compiled Jan 27 2014, 08:56:32                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
*        May not be used in a product                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: digit_battery                                         *
* Dimensions:  13 * 13                                               *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmdigit_battery;

static GUI_CONST_STORAGE unsigned short _acdigit_battery[] = {
  0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0043, 0x092A, 0x0000, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0084, 0x1AB5, 0x08C6, 0x0000, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x08A5, 0x1AD6, 0x1AD6, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x0000, 0x08E7, 0x1AF7, 0x1B18, 0x11EF, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x0929, 0x1AF8, 0x1B18, 0x1B18, 0x08E7, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0x118C, 0x1B18, 0x1B18, 0x1B18, 0x1B18, 0x11EF, 0x094A, 0x08A6, 0x0021, 0x0000, 0x0000,
  0x0000, 0x11CE, 0x1B18, 0x1B18, 0x1B18, 0x1B18, 0x1B18, 0x1B18, 0x1B18, 0x1B18, 0x11CE, 0x0000, 0x0000,
  0x0000, 0x0021, 0x08A6, 0x094A, 0x11EF, 0x1B18, 0x1B18, 0x1B18, 0x1B18, 0x118C, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x0000, 0x08E7, 0x1B18, 0x1B18, 0x1AF8, 0x0929, 0x0000, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x0000, 0x11EF, 0x1B18, 0x1AF7, 0x08E7, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x0000, 0x1AD6, 0x1AD6, 0x08A5, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x08C6, 0x1AB5, 0x0084, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x092A, 0x0043, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000
};

GUI_CONST_STORAGE GUI_BITMAP bmdigit_battery = {
  13, // xSize
  13, // ySize
  26, // BytesPerLine
  16, // BitsPerPixel
  (unsigned char *)_acdigit_battery,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMPM565
};

/*************************** End of file ****************************/
