/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin (Demo version) V5.24.            *
*        Compiled Jan 27 2014, 08:56:32                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
*        May not be used in a product                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: digit_afternoon                                       *
* Dimensions:  20 * 8                                                *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmdigit_afternoon;

static GUI_CONST_STORAGE unsigned short _acdigit_afternoon[] = {
  0x1252, 0x1B18, 0x1B18, 0x1B18, 0x1B18, 0x1B18, 0x1B18, 0x1B18, 0x1B18, 0x118C, 0x0000, 0x1252, 0x1AD7, 0x08E8, 0x08C6, 0x08C6, 0x08C6, 0x08C6, 0x08C6, 0x0063,
  0x0000, 0x0000, 0x0000, 0x1252, 0x1252, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0063, 0x1252, 0x1252, 0x1252, 0x1AB5, 0x1B18, 0x1252, 0x1252, 0x1252, 0x0929,
  0x0000, 0x0000, 0x0000, 0x1252, 0x1252, 0x0885, 0x118C, 0x0063, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x118C, 0x1B18, 0x0000, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x1252, 0x1252, 0x0000, 0x1AB5, 0x11EF, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x118C, 0x1B18, 0x0000, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x1252, 0x1252, 0x0000, 0x0929, 0x1B18, 0x0885, 0x0000, 0x1252, 0x1B18, 0x1B18, 0x1B18, 0x1B18, 0x1B18, 0x1B18, 0x1B18, 0x1B18, 0x1B18,
  0x0000, 0x0000, 0x0000, 0x1252, 0x1252, 0x0000, 0x0000, 0x094B, 0x08E8, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x118C, 0x1B18, 0x0000, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x1252, 0x1252, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x118C, 0x1B18, 0x0000, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x11AE, 0x11AE, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0929, 0x1252, 0x0000, 0x0000, 0x0000, 0x0000
};

GUI_CONST_STORAGE GUI_BITMAP bmdigit_afternoon = {
  20, // xSize
  8, // ySize
  40, // BytesPerLine
  16, // BitsPerPixel
  (unsigned char *)_acdigit_afternoon,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMPM565
};

/*************************** End of file ****************************/
